name: CI/CD Pipeline

on:
  push:
    branches: [ develop ]
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy app
        run: |
          pwd
          ls -la
          git pull
          docker-compose up -d --build
