name: CI/CD Deploy to EC2


on:
  push:
    branches:
      - develop
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Compress source code
        run: |
          tar --exclude=app.tar.gz \
              --exclude=__pycache__ \
              --exclude=.git \
              --exclude=node_modules \
              --ignore-failed-read \
              --czf app.tar.gz .
      - name: Copy code to EC2
        env:
          HOST: ${{ secrets.VM_HOST }}
          USER: ${{ secrets.VM_USER }}
          PORT: ${{ secrets.VM_PORT }}
        run: |
          scp -o StrictHostKeyChecking=no -p $PORT app.tar.gz $USER@$HOST:/home/$USER/app.tar.gz

      - name: Deploy on EC2
        env:
          HOST: ${{ secrets.VM_HOST }}
          USER: ${{ secrets.VM_USER }}
          PORT: ${{ secrets.VM_PORT }}
        run: |
          ssh -o StrictHostKeyChecking=no -p